/**
 * @stra/transform - Core transformer
 *
 * Orchestrates the transform pipeline:
 * 1. Detect module type
 * 2. Run plugin transform hooks
 * 3. Apply built-in transforms if needed
 */

import { createLogger, type Logger, hashContent } from '@stra/shared-node';
import type { PluginContainer } from '@stra/plugin';
import { detectModuleType, needsTransform, isScriptType } from './detect';
import { scanImports } from './scanner';
import type { TransformOptions, TransformOutput, ModuleType } from './types';

export interface TransformerOptions {
  /** Plugin container for transform hooks. */
  pluginContainer?: PluginContainer;
  /** Logger instance. */
  logger?: Logger;
}

export class Transformer {
  private pluginContainer?: PluginContainer;
  private logger: Logger;

  constructor(options: TransformerOptions = {}) {
    this.pluginContainer = options.pluginContainer;
    this.logger = options.logger ?? createLogger({ namespace: 'transform' });
  }

  /** Transform a source file. */
  transform(options: TransformOptions): TransformOutput {
    const moduleType = detectModuleType(options.id);
    let code = options.code;
    let map: string | undefined;
    const isDev = options.dev ?? false;

    // Run plugin transforms
    if (this.pluginContainer) {
      const pluginResult = this.pluginContainer.transform({
        code,
        id: options.id,
        moduleType,
      });
      code = pluginResult.code;
      map = pluginResult.map;
    }

    // For script types, scan imports for dependency tracking
    let deps: string[] | undefined;
    if (isScriptType(moduleType)) {
      deps = scanImports(code);
    }

    // CSS → JS module transform (inject style)
    if (moduleType === 'css' && isDev) {
      code = this.transformCSSToJSModule(code, options.id);
    }

    // JSON → JS module transform (default export)
    if (moduleType === 'json') {
      code = this.transformJSONToJSModule(code);
    }

    return {
      code,
      map,
      deps,
      moduleType,
    };
  }

  /** Check if a file needs transformation. */
  needsTransform(id: string): boolean {
    return needsTransform(detectModuleType(id));
  }

  /** Get the module type for a file. */
  getModuleType(id: string): ModuleType {
    return detectModuleType(id);
  }

  /** Transform CSS to a JS module that injects a <style> tag. */
  private transformCSSToJSModule(css: string, id: string): string {
    const contentHash = hashContent(css, 6);
    return [
      `// Generated by @stra/transform from ${id}`,
      `const __css = ${JSON.stringify(css)};`,
      `const __id = 'stra-style-${contentHash}';`,
      `if (typeof document !== 'undefined') {`,
      `  let el = document.getElementById(__id);`,
      `  if (!el) {`,
      `    el = document.createElement('style');`,
      `    el.id = __id;`,
      `    document.head.appendChild(el);`,
      `  }`,
      `  el.textContent = __css;`,
      `}`,
      `export default __css;`,
    ].join('\n');
  }

  /** Transform JSON to a JS module with default export. */
  private transformJSONToJSModule(json: string): string {
    return [
      `// Generated by @stra/transform`,
      `const __data = ${json};`,
      `export default __data;`,
    ].join('\n');
  }
}

/** Create a transformer instance. */
export function createTransformer(options?: TransformerOptions): Transformer {
  return new Transformer(options);
}
